### ISSUE TITLE
vector!(shared_ptr!T)) crash

### ISSUE THREAD

**Issue by p0nce** [Inochi2D/numem#2]
Consider the following unittest:
```d
unittest
{
    import core.stdc.stdio;
    import numem.vector;

    class A
    {   
    }
    shared_ptr!A a = shared_new!A();
    vector!(shared_ptr!A) v;
    v ~= a; // crash on Windows x86_64
}
```
On Windows x86_64 (but not x86 32-bit), with either DMD or LDC, a segfault occur because of an unaligned atomic operation near null.

**Comment by LunaTheFoxgirl** [comment]
I have found this crash yesterday and have it fixed in my local version, will be pushing the fix later this evening.

**Comment by p0nce** [comment]
https://github.com/Inochi2D/numem/pull/3
