### ISSUE TITLE
Comparison will be interesting

### ISSUE THREAD

**Issue by cyrusmsk** [Inochi2D/numem#9]
Something significantly different from other similar projects?
https://code.dlang.org/packages/btl
https://code.dlang.org/packages/automem

Would be interesting to see small "comparison" list why users should use this solution over others?

**Comment by LunaTheFoxgirl** [comment]
It's not exactly a matter of "should use", this library is made to cover the needs of Inochi2D.
numem is quickly evolving into its own little nogc standard library.
